name: Deploy Application


on: 

  push:

    branches:
       
      - main


jobs:

  create-deployment-artifacts:

    name: Create deployment artifacts

    runs-on: ubuntu-latest

    outputs:
      
      deployment-matrix: ${{ steps.export-deployment-matrix.outputs.deployment-matrix }}

    steps:

      - uses: actions/checkout@v2


      - name: Compile CSS and Javascript

        run:

          npm install

          npm run prod

      - name: Configure php 8.0

        uses: shivammathur/setup-php@master

        with:

          php-version: 8.0

          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

      - name: install Composer dependencies

        run: composer install --no-dev --no-interaction --prefer-dist


      - name: Create deployment artifacts

        env:

          GITHUB_SHA: ${{ github.sha }}

        run: tar -czf *${GITHUB_SHA}*.tar.gz --exclude=*.git --exclude=node_modules *


      - name: Store artifact for distribution

        uses: actions/upload-artifact@v2

        with:

          name: app-build

          path: ${{ github.sha}}.tar.gz

      - name: Expoer deployment matrix

        id: export-deployment-mtrix

        run: |

          JSON="$(cat ./deploment-config.json)"

          JSON="$(JSON//'%'/'%25')"

          JSON="$(JSON//$'n'/'%0A')"

          JSON="$(JSON//$'n'/'%0D')"

          echo " ::set-output name=deployment-matrix ::$JSON"

  prepare-release-on-servers:

    runs-on: ubuntu-latest

    needs: create-deployment-artifacts

    strategy:
      
      matrix:

        server: ${{ fromJson(needs.create-deployment-artifacts..outputs.deployment-matrix) }}

    steps:

        - uses: actions/download-artifact@v2

          with: 

            name: app-build